apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: platform
  name: circleci-exporter
  labels:
    app: circleci-exporter
    product: platform
    process: exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: circleci-exporter
        product: platform
        process: exporter
    spec:
      containers:
      - env:
        - name: CIRCLE_TOKEN
          valueFrom:
            secretKeyRef:
              key: CIRCLE_TOKEN
              name: circleci-exporter
        name: circleci-exporter
        image: vivareal/circleci-exporter:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources:
            requests:
              memory: 250Mi
              cpu: 200m
            limits:
              memory: 250Mi
              cpu: 200m
      restartPolicy: Always
