apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "5000"
    prometheus.io/scrape: "true"
  namespace: platform
  name: circleci-exporter
  labels:
    app: circleci-exporter
    product: platform
    process: exporter
spec:
  ports:
  - port: 9104
    protocol: TCP
    targetPort: 5000
  selector:
    app: circleci-exporter
    product: platform
    process: exporter
